### ISSUE TITLE
v0.0.1 Release

### ISSUE THREAD

**Issue by JeremyLWright** [thejohnfreeman/autocheck#11]
I want to pull this into a few projects and it is helpful to have a version number. Could you make a release for the current HEAD, please?

**Comment by thejohnfreeman** [comment]
Do you just want a tag?

**Comment by JeremyLWright** [comment]
That works! Thank you!

Sent from my StarTac
________________________________

**Comment by thejohnfreeman** [comment]
I'm tagging it v1.0.0 to promise a stable API. There hasn't been any contention over the API, so I don't expect a guarantee to be an issue.
